/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2018-11-17 15:49:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/Fernanda%20Cosme/Documents/GitHub/inside.backend/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/inside/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153395882000L));
    _jspx_dependants.put("jar:file:/C:/Users/Fernanda%20Cosme/Documents/GitHub/inside.backend/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/inside/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153395882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1541796894586L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"pt-br\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>Inside Co.</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("    <link href=\"css/styles.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("    <link href=\"css/simple-sidebar.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- <script src=\"https://use.fontawesome.com/0fecb3c89d.js\"></script> -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.2.0/css/all.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.2.0/css/v4-shims.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"section-primary\" id=\"login-page\">\r\n");
      out.write("<div class=\"invisible-xs invisible-xxs\">\r\n");
      out.write("  <div class=\"container col-lg-offset-3 col-md-offset-3 pdd-100-lg-t\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-md-3 col-lg-3 col-lg-offset-2 \">\r\n");
      out.write("        <img class=\"img-responsive\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/logo_2.png\">\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"row\">\r\n");
      out.write("    <div class=\"col-lg-4 col-md-4 col-lg-offset-4\">\r\n");
      out.write("      <div class=\"container col-md-12 col-lg-12 pdd-15-lg-t pdd-15-md-t pdd-15-md-b pdd-15-lg-b\">\r\n");
      out.write("        <div class=\"mat-card-kit  \">\r\n");
      out.write("          <div class=\"container-fluid  pdd-30-lg-t pdd-30-md-t pdd-30-md-b pdd-30-lg-b\">\r\n");
      out.write("          \t<form action=\"login\" method=\"post\">\r\n");
      out.write("\t            <div class=\"row pdd-15-md-t pdd-15-lg-t\">\r\n");
      out.write("\t              <div class=\"col-lg-12 col-md-5\">\r\n");
      out.write("\t                <div class=\"col-lg-12 col-md-2\">\r\n");
      out.write("\t                  <h5 class=\"text-danger text-bold text-center\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <div class=\"row pdd-15-md-t pdd-15-lg-t\">\r\n");
      out.write("\t              <div class=\"col-lg-3 col-md-5\">\r\n");
      out.write("\t                <div class=\"col-lg-3 col-md-2\">\r\n");
      out.write("\t                  <h5 class=\"text-primary text-bold text-center\">Login</h5>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t              <div class=\"col-lg-8 col-md-8 pdd-15-md-t \">\r\n");
      out.write("\t                <input type=\"text\" name=\"login\" class=\"form-control text-primary\" value=\"janaina.abc3@gmail.com\">\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <div class=\"row pdd-15-lg-t pdd-15-md-t\">\r\n");
      out.write("\t              <div class=\"col-lg-3 col-md-3\">\r\n");
      out.write("\t                <h5 class=\"text-primary text-bold text-center\">Senha</h5>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t              <div class=\"col-lg-8 col-md-8 \">\r\n");
      out.write("\t                <input type=\"password\" name=\"senha\" class=\"form-control text-primary\" value=\"49560\">\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <div class=\"row\">\r\n");
      out.write("\t              <div class=\"col-lg-8 col-md-8 col-lg-offset-2 pdd-50-lg-t pdd-50-md-t\">\r\n");
      out.write("\t                <!-- <a href=\"demandas.html\"> -->\r\n");
      out.write("\t                <button type=\"submit\" class=\" btn btn-lg btn-primary text-white btn-block\">Entrar</button>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t      \t</form>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"invible-md invisible-lg invisible-xlg\" style=\"overflow-x:hidden !important\">\r\n");
      out.write("    <div class=\"container pdd-50-xs-t pdd-50-xxs-t\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-xs-9 col-xxs-9 col-xs-offset-1 col-xxs-offset-1 \">\r\n");
      out.write("          <img class=\"img-responsive\" src=\".\\images\\logo_2.png\">\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-xs-10 col-xxs-10 col-xs-offset-1 col-xxs-offset-1\">\r\n");
      out.write("        <div class=\"container-fluid col-xs-12 col-xxs-12 pdd-15-xxs-t pdd-15-xs-t pdd-15-xs-b pdd-15-xxs-b\">\r\n");
      out.write("          <div class=\"mat-card-kit  \">\r\n");
      out.write("          <form action=\"login\" method=\"post\">\r\n");
      out.write("          <div class=\"row pdd-15-md-t pdd-15-lg-t\">\r\n");
      out.write("             <div class=\"col-lg-12 col-md-5\">\r\n");
      out.write("               <div class=\"col-lg-12 col-md-2\">\r\n");
      out.write("                 <h5 class=\"text-danger text-bold text-center\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("               </div>\r\n");
      out.write("             </div>\r\n");
      out.write("           </div>\r\n");
      out.write("            <div class=\"container pdd-15-xxs-t pdd-15-xs-t pdd-15-xs-b pdd-15-xxs-b\">\r\n");
      out.write("              <div class=\"row pdd-15-xs-t pdd-15-xxs-t\">\r\n");
      out.write("                <div class=\"col-xxs-12 col-xs-12\">\r\n");
      out.write("                  <div class=\"col-xxs-12 col-xs-12\">\r\n");
      out.write("                    <h5 class=\"text-primary text-bold text-center\">Login</h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-xxs-12 col-xs-12 pdd-10-xs-t pdd-10-xxs-t \">\r\n");
      out.write("                   <input type=\"text\" name=\"login\" class=\"form-control text-primary\" value=\"dennis.siqueira@gmail.com\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"row pdd-15-xxs-t pdd-15-xs-t\">\r\n");
      out.write("                <div class=\"col-xxs-12 col-xs-12\">\r\n");
      out.write("                  <h5 class=\"text-primary text-bold text-center\">Senha</h5>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-xs-12 col-xxs-12 \">\r\n");
      out.write("                  <input type=\"password\" name=\"senha\" class=\"form-control text-primary\" value=\"61071\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("    \r\n");
      out.write("                <div class=\"col-xxs-12 col-xs-12 col-xxs-offset-2 pdd-30-xxs-t pdd-30-xs-t pdd-15-xxs-b pdd-15-xs-b\">\r\n");
      out.write("                  <a href=\"demandas\">\r\n");
      out.write("    \r\n");
      out.write("                    <button type=\"submit\" class=\" btn btn-lg btn-primary text-white btn-block\">Entrar</button>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              </form>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- /#wrapper -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap core JavaScript -->\r\n");
      out.write("  <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"javascripts/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Menu Toggle Script -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
