/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2018-11-17 15:59:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.importViews;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class SidebarAdmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- <div id=\"sidebar-wrapper\" class='invisible-xs invisible-xxs'> -->\r\n");
      out.write("<div id=\"sidebar-wrapper\" class='invisible-xs invisible-xxs' style=\"background: #264c54 !important\">\r\n");
      out.write("\t<ul class=\"sidebar-nav\">\r\n");
      out.write("\t\t<li class=\"sidebar pdd-15-md-t pdd-15-lg-t pdd-15-xlg-t pdd-30-md-b pdd-30-lg-b pdd-30-xlg-b\">\r\n");
      out.write("\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-11 col-lg-10 col-lg-offset-1 col-md-offset-1 pdd-15-md-t pdd-15-lg-t pdd-15-md-b pdd-15-lg-b\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-9 col-lg-9 col-lg-offset-1 col-md-offset-1 pdd-15-md-b pdd-15-lg-b\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <img src=\"./images/analyst_user.png\" class=\"img-responsive img-circle\" alt=\"\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t<i class='text-white fas fa-users-cog fa-4x icon-admin-sidebar'></i>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12 col-lg-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"text-white text-bold text-center\">Gestor de Projetos</h4>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- <a href=\"#\"><h6 class=\"text-white text-left\"><i class='fa fa-edit'></i> Editar perfil</h6></a> -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t<!-- \t\t\t\t\t\t<div class=\"col-md-10 col-lg-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h5 class=\"text-white text-center\"><i class='fa fa-edit text-primary'></i> Editar perfil</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<div class=\"line-white \"></div>\r\n");
      out.write("\t\t<div class=\"menu pdd-30-md-t pdd-30-lg-t\">\r\n");
      out.write("\t\t\t<li class=\"pdd-30-md-t pdd-30-lg-t\"><a href=\"projetos\"\r\n");
      out.write("\t\t\t\tclass=\"text-white\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"fas fa-tasks text-white pdd-15-lg-r\" aria-hidden=\"true\"\r\n");
      out.write("\t\t\t\t\tstyle=\"display: inline\"></i> Projetos</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"novoProjeto\" class=\"text-white\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"fas fa-clipboard-check text-white pdd-15-lg-r\"\r\n");
      out.write("\t\t\t\t\taria-hidden=\"true\" style=\"display: inline\"></i> Cadastrar novo\r\n");
      out.write("\t\t\t\t\tprojeto</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"clientes\" class=\"text-white\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"far fa-address-card  text-white pdd-15-lg-r\"\r\n");
      out.write("\t\t\t\t\taria-hidden=\"true\" style=\"display: inline\"></i> Clientes</a></li>\t\t\t\t\r\n");
      out.write("\t\t\t<li><a href=\"listar_analistas\" class=\"text-white\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"fas fa-users text-white pdd-15-lg-r\" aria-hidden=\"true\"\r\n");
      out.write("\t\t\t\t\tstyle=\"display: inline\"></i> Analistas\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"cronograma\" class=\"text-white\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"fas fa-chart-line text-white pdd-15-lg-r\" aria-hidden=\"true\"\r\n");
      out.write("\t\t\t\t\tstyle=\"display: inline\"></i> Cronograma\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t<!--<li>\r\n");
      out.write("              <a href=\"cadastroCliente.html\" class=\"text-white\"> <i class=\"far fa-address-card  text-white pdd-15-lg-r\" aria-hidden=\"true\" style=\"display:inline\"></i>\r\n");
      out.write("               Cadastrar novo Cliente</a>\r\n");
      out.write("            </li> -->\r\n");
      out.write("            \r\n");
      out.write("\t\t\t<!-- \t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"desempenhoAdmin.html\" class=\"text-white\"> <i class=\"fas fa-chart-line text-white pdd-15-lg-r\" aria-hidden=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t style=\"display:inline\"></i> Desempenho</a>\r\n");
      out.write("\t\t\t\t\t</li> -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<div class=\"pdd-50-lg-t\">\r\n");
      out.write("\t\t<div class=\"pdd-500-lg-t\">\r\n");
      out.write("\t\t\t<div class=\"col-md-9 col-lg-9 col-lg-offset-1\">\r\n");
      out.write("\t\t\t\t<img class=\"img-responsive\" src=\"./images/logo_2.png\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
